Controllers/RoleController.cs
using DatingIdentity.Areas.Identity.Data;
using DatingIdentity.ModelViews;
using DatingIdentity.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DatingIdentity.Controllers
{
    [Authorize(Roles="Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<DatingIdentityUser> _userManager;


        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<DatingIdentityUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }



        // GET: AdminController
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }


        // GET: AdminController/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View(new IdentityRole());
        }

        // POST: AdminController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            if(ModelState.IsValid)
            {
               IdentityResult result = await _roleManager.CreateAsync(role);
           
           
            if(result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            
            foreach(IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
           
            return View(role);
        }

        //private void RoleDropDownList(object selectedRole = null)
        //{
        //    var roleQuery = from d in _roleManager.Roles
        //                    orderby d.Name
        //                    select d;

        //    ViewBag.Id = new SelectList(roleQuery.AsNoTracking(), "Id", "Name", selectedRole);

        //}

        [HttpGet]
        public async Task<ActionResult> EditRole(string Id)
        {
            if (Id == null)
            {
                return NotFound();
            }

            var roleExist = await _roleManager.FindByIdAsync(Id);

            if (ModelState.IsValid)
            {

                if (roleExist == null)
                {
                    ViewBag.ErrorMessage = $"Le rôle avec l'ID {Id} n'a pas été trouvé.";
                    return View("NotFound");
                }

                var model = new UserViewModel
                {
                    Id = roleExist.Id,
                    RoleName = roleExist.Name
                };

                foreach (var user in _userManager.Users)
                {
                    if (await _userManager.IsInRoleAsync(user, roleExist.Name))
                    {
                        model.Users.Add(user.UserName);
                    }
                }

                return View(model);
            }
            //RoleDropDownList(Id);
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> EditRole(UserViewModel model)
        {
 
            var roleExist = await _roleManager.FindByIdAsync(model.Id);

            if (ModelState.IsValid)
            {

                if (roleExist == null)
                {
                    ViewBag.ErrorMessage = $"Le rôle avec l'ID {model.Id} n'a pas été trouvé.";
                    return View("NotFound");
                }
                else
                {
                    roleExist.Name = model.RoleName;
                   var result = await _roleManager.UpdateAsync(roleExist);

                    if(result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }

                    foreach(var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                    return View(model);
                } 
                
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(string roleId)
        {
            ViewBag.roleId = roleId;

            var role = await _roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Le rôle avec l'Id {roleId} n'a pas été trouvé";
                return View("NotFound");
            }
            var model = new List<UserRoleViewModel>();

            foreach(var user in _userManager.Users)
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    UserId = user.Id,
                    Email = user.Email
                };

                if(await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRoleViewModel.IsSelected = true;
                }
                else
                {
                    userRoleViewModel.IsSelected = false;
                }

                model.Add(userRoleViewModel);
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, string roleId)
        {
         

            var role = await _roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Le rôle avec l'id {roleId} n'a pas été trouvé";
                return View("NotFound");
            }

            for(int i = 0; i < model.Count; i++)
            {
              var user =  await _userManager.FindByIdAsync(model[i].UserId);

                IdentityResult result = null;

                if (model[i].IsSelected && !(await _userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await _userManager.AddToRoleAsync(user, role.Name);

                }
                else if (!model[i].IsSelected && await _userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await _userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if(result.Succeeded)
                {
                    if (i < (model.Count - 1))
                    {
                        continue;
                    }else{
                        return RedirectToAction("EditRole", new { Id = roleId });
                    }
                }
            }
                        
           return RedirectToAction("EditRole", new { Id = roleId });
        }



    }
}

Views/Role/Create.cshtml
@model Microsoft.AspNetCore.Identity.IdentityRole

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Création nouveau rôle</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <Input asp-for="Name" class="form-control" />
                <input type="submit" value="Ajouter" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Role/EditRole.cshtml
@model DatingIdentity.ModelViews.UserViewModel

@{
    ViewData["Title"] = "editRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Attribution des rôles</h1>


<hr />

    
        <form asp-action="editRole" class="container">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group row">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <label asp-for="RoleName" class="control-label"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <input type="submit" value="Modifier" class="btn btn-primary mr-2" />
                <a asp-action="Index" class="btn btn-primary">Retour à la liste</a>
            </div>
        </form>
    


<div class="card">
    <div class="card-header">
        <h3>Utilisateurs</h3> 
    </div>
    <div class="card-body">
        @if(Model.Users.Any())
        {
            foreach(var user in Model.Users)
                {
                    <h5 class="card-title">@user</h5>
                }
            }
            else
            {
                <h5 class="card-title">Personne ne détient ce rôle.</h5>
            }
    </div>
    <div class="card-footer">
        <a asp-action="EditUsersInRole" asp-controller="Role" asp-route-roleId="@Model.Id" class="btn btn-primary"> Ajout ou Supprimer un utilisateur</a>        
    </div>
</div>

Views/Role/EditUsersInRole.cshtml
@model List<DatingIdentity.ViewModels.UserRoleViewModel>

@{
    var roleId = ViewBag.roleId;
}



<h4>Affectation Rôle aux Utilisateurs</h4>
<hr />

    
        <form method="post">
            <div class="card">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="card-header">
                    <h3>Ajout ou suppression d'utilisateurs pour le rôle</h3>
                </div>
                <div class="card-body">
                
                    @for(int i =0; i<Model.Count; i++)
            {
                    <div class="form-check">
                        <input type="hidden" asp-for="@Model[i].UserId" />
                        <input type="hidden" asp-for="@Model[i].Email" />
                        <input asp-for="@Model[i].IsSelected" class="form-check-input" />
                        <label asp-for="@Model[i].IsSelected" class="form-check-label">
                            @Model[i].Email
                        </label>
                    </div>
            }


                </div>
                <div class="card-footer">                    
                        <input type="submit" value="Enregistrer" class="btn btn-primary" />  
                        <a asp-action="editRole" asp-route-id="@roleId" class="btn btn-primary">Retour</a>
                </div>
            </div>
        </form>



<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Role/Index.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityRole>
@{
    ViewData["Title"] = "Index";
}

<h1>Le type de Rôles</h1>
<a asp-action="Create">Créer</a>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <td>Id</td>
            <td>Name</td>
            <td>Actions</td>
        </tr>
    </thead>

    <tbody>
        @if (Model.Any())
        {
            @foreach (var role in Model)
            {
                <tr>
                    <td>@role.Id</td>
                    <td>@role.Name</td>
                    <td>
                        <a asp-action="editRole" asp-route-id="@role.Id">Modifier</a> |
                        <a asp-action="Delete" asp-route-id="@role.Id">Supprimer</a>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="3">
                    Il n'y a pas de rôle existant
                </td>
            </tr>
        }
    </tbody>
</table>